### ISSUE TITLE
SPM path is required?

### ISSUE THREAD

**Issue by ftadel** [IntrAnatSEEGSoftware/IntrAnat#3]
![image](https://user-images.githubusercontent.com/6920058/37418447-86dc1ba4-27b2-11e8-8cfa-7a638affc4c1.png)

Why do you need to know where SPM is if it simply has to be in the Matlab path?
An annoying fact is that I will have Matlab on my Windows drive (and SPM with it), and IntrAnat/BrainVISA on my Ubuntu drive. Is it something I'll be able to sort out easily?

**Comment by pdeman** [comment]
Hi, no it doesn't have to be in matlab path anymore.
there was a problem because most of people have different spm versions on their computer and doens't put any in the path to avoid confusion.
many software depend on spm but depend on different version of spm.
so softwares add themselfes the good spm version using genpath and addpath.
but users didn't want to have to add any spm path durably.
so you have to provide to IntrAnat a spm path and it will do a addpath(genpath()).
I think we didn't take the spm path specified into brainvisa because we didn't switch at the same time at some major spm udpate.
but now we could probably read the spm path provide into brainvisa.

for now just specify the path in the preferences tab of ImageImport and save.
I'll look in to this soon.

**Comment by ftadel** [comment]
> but users didn't want to have to add any spm path durably.

I totally agree. The paths for the various programs should always be set dynamically, to avoid conflicts.

**Comment by ftadel** [comment]
(you should just remove the instruction to add SPM to the path from the installation doc)
